const API_URI = process.env.EXPO_PUBLIC_API_URI ?? "";
const UPLOAD_URI = process.env.EXPO_PUBLIC_UPLOAD_URI ?? "";
const WEBVIEW_LOGIN = process.env.EXPO_PUBLIC_WEBVIEW_LOGIN ?? "";
const WEBVIEW_SIGNUP = process.env.EXPO_PUBLIC_WEBVIEW_SIGNUP ?? "";
const WEBVIEW_FORGOT = process.env.EXPO_PUBLIC_WEBVIEW_FORGOT ?? "";
const WEBVIEW_MEMBER = process.env.EXPO_PUBLIC_WEBVIEW_MEMBER ?? "";
const WEBVIEW_GROW_CONTROL = process.env.EXPO_PUBLIC_WEBVIEW_GROW_CONTROL ?? "";
const WEBVIEW_FINANCE = process.env.EXPO_PUBLIC_WEBVIEW_FINANCE ?? "";
const WEBVIEW_CLUB_PROFILE = process.env.EXPO_PUBLIC_WEBVIEW_CLUB_PROFILE ?? "";
const MAPBOX_ACCESS_TOKEN = process.env.EXPO_PUBLIC_MAPBOX_ACCESS_TOKEN ?? "";
const TILESERVER = process.env.EXPO_PUBLIC_TILESERVER ?? "";

export {
  API_URI,
  UPLOAD_URI,
  WEBVIEW_LOGIN,
  WEBVIEW_SIGNUP,
  WEBVIEW_FORGOT,
  WEBVIEW_MEMBER,
  WEBVIEW_GROW_CONTROL,
  WEBVIEW_FINANCE,
  WEBVIEW_CLUB_PROFILE,
  MAPBOX_ACCESS_TOKEN,
  TILESERVER
};
